### ISSUE TITLE
nextGenInferenceVariGraph.pl --collect 3 Picard Error

### ISSUE THREAD

**Issue by hgibling** [AlexanderDilthey/MHC-PRG#10]
Hello, 

I would like to use MHC-PRG, but can’t seem to get step 4 `--collect 3` working on the supplied `AA02O9Q_Z2.bam`. The error occurs when running `picard` at line 549 of `nextGenInferenceVariGraph.pl`:

```
net.sf.picard.sam.SamToFastq INPUT=path/to/MHC-PRG/data/samples/BAMs/AA02O9Q_Z2.bam OUTPUT_PER_RG=true OUTPUT_DIR=/path/to/MHC-PRG/tmp/readReMapping/kMerCount__GS_nextGen_varigraph3_AA02O9Q_Z2_31_remapping/reads    RE_REVERSE=true INCLUDE_NON_PF_READS=false READ1_TRIM=0 READ2_TRIM=0 INCLUDE_NON_PRIMARY_ALIGNMENTS=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
Executing as ... on Linux 3.14.27 amd64; Java HotSpot(TM) 64-Bit Server VM 1.6.0_21-b06; Picard version: 1.83(1319)
net.sf.picard.sam.SamToFastq done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2028273664
FAQ:  http://sourceforge.net/apps/mediawiki/picard/index.php?title=Main_Page
Exception in thread "main" java.lang.NullPointerException
        at net.sf.picard.sam.SamToFastq.doWork(SamToFastq.java:148)
        at net.sf.picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:177)
        at net.sf.picard.sam.SamToFastq.main(SamToFastq.java:119)
PICARD extraction command java -Xmx2g -jar path/to/picard-tools-1.83/SamToFastq.jar INPUT=path/to/MHC-PRG/data/samples/BAMs/AA02O9Q_Z2.bam OUTPUT_PER_RG=TRUE OUTPUT_DIR=path/to/MHC-PRG/tmp/readReMapping//kMerCount__GS_nextGen_varigraph3_AA02O9Q_Z2_31_remapping/reads/ failed at path/to/MHC-PRG/src/nextGenInferenceVariGraph.pl line 559.
```
I have `picard v 1.83` installed as noted in the `README`. 

Looking at `AA02O9Q_Z2.bam`, there don’t seem to be any read groups listed when using `samtools view -H` —could this be causing an issue since the `picard` command requires the `OUTPUT_PER_RG=TRUE` option?

I’m going to try again with the latest version of `picard` (2.1.1), but wanted to check with you in case you were aware of this issue and had any advice.

Thank you,
Heather

**Comment by AlexanderDilthey** [comment]
Hi Heather,

I haven't come across this problem before. Can you reproduce the problem if you execute the picard command manually from the command line? 

Alex

**Comment by hgibling** [comment]
Hi Alex,

Yes, I get the same error message when executing just the picard command on `AA02O9Q_Z2.bam`, with both picard versions 1.83 and 2.1.1. The command does work if I use one of our own bam files that has read groups as checked with `samtools view -H` (`AA02O9Q_Z2.bam` does not have read groups listed). 

Is it vital to split the bam by read group? Could equivalent results be obtained by splitting the bam by paired ends?

**Comment by AlexanderDilthey** [comment]
No, the read groups don't really matter - we only need reconstructed paired-end FASTQ. I am just wondering where this problem is coming from, as exactly the same command has worked here locally. Can you try to remove the OUTPER_PER_RG switch and re-run?

Alex


Date: Thu, 28 Apr 2016 08:32:37 -0700

**Comment by hgibling** [comment]
Hi Alex,

Changed to `java -Xmx2g -jar path/to/picard-tools-1.83/SamToFastq.jar INPUT=path/to/MHC-PRG/data/samples/BAMs/AA02O9Q_Z2.bam FASTQ=first SECOND_END_FASTQ=second`

It progresses further, but still doesn't complete:
```
INFO    2016-04-28 15:35:44     SamToFastq      Processed     1,000,000 records.  Elapsed time: 00:00:27s.  Time for last 1,000,000:   27s.  Last read position
: 1:1,879,878
INFO    2016-04-28 15:36:13     SamToFastq      Processed     2,000,000 records.  Elapsed time: 00:00:56s.  Time for last 1,000,000:   28s.  Last read position
: 1:3,766,972

[...]

INFO    2016-04-28 20:42:41     SamToFastq      Processed   561,000,000 records.  Elapsed time: 05:07:24s.  Time for last 1,000,000:   27s.  Last read position
: 16:88,575,231
[Thu Apr 28 20:43:07 EDT 2016] net.sf.picard.sam.SamToFastq done. Elapsed time: 307.84 minutes.
Runtime.totalMemory()=2142306304
FAQ:  http://sourceforge.net/apps/mediawiki/picard/index.php?title=Main_Page
Exception in thread "main" net.sf.samtools.SAMFormatException: SAM validation error: ERROR: Record 561917122, Read name ERR091571.55385293, MAPQ should be 0 for unmapped read.
        at net.sf.samtools.SAMUtils.processValidationErrors(SAMUtils.java:448)
        at net.sf.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:540)
        at net.sf.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:521)
        at net.sf.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:480)
        at net.sf.samtools.SAMFileReader$AssertableIterator.next(SAMFileReader.java:669)
        at net.sf.samtools.SAMFileReader$AssertableIterator.next(SAMFileReader.java:647)
        at net.sf.picard.sam.SamToFastq.doWork(SamToFastq.java:130)
        at net.sf.picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:177)
        at net.sf.picard.sam.SamToFastq.main(SamToFastq.java:119)
```

**Comment by AlexanderDilthey** [comment]
Hi Heather,

Try setting the validation stringency parameter to "lenient", and could you also send me an md5sum of the BAM?

Alex
________________________________

**Comment by hgibling** [comment]
Hi Alex,

Ok, running that now. In the meantime:
```
$ md5sum -b AA02O9Q_Z2.bam 
8ce03a6131d715de0e789a2e9ce307f4 *AA02O9Q_Z2.bam
```

**Comment by hgibling** [comment]
So this does work on the sample file in command line. I've modified the perl script and it seems to be running fine.

**Comment by AlexanderDilthey** [comment]
md5sum is correct! For reference, can you send me exactly the line of code that works for you? I'll test locally and then modify the repository.

**Comment by hgibling** [comment]
Sure. Line 545 is now:

```
my $cmd = qq(java -Xmx2g -jar ${PICARD_SAM2FASTQ} INPUT=${BAM_file} FASTQ=${remapping_dir_reads}/file_1.fastq SECOND_END_FASTQ=${remapping_dir_reads}/file_2.fastq VALIDATION_STRINGENCY=LENIENT);
```

Thanks for your help!

**Comment by AlexanderDilthey** [comment]
I have integrated the changes into our repository. Thank you for your help. Let me know if you run into further issues.
