### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by yluo86** [AlexanderDilthey/MHC-PRG#11]
Hi Alex,

I tried both GCC 4.7.2 and GCC 5.2.0 to install MHC*PRG, but both stopped at the following stage:

 g++  -I/${boostpath}/boost_1.52.0/ -IGraph -I/path/bamtools/include -I/${bamtoolspath}/bamtools/src  -ggdb -O2 -fopenmp -std=gnu++0x -fstack-protector-all ../obj/GenotypePanel.o ../obj/HaplotypePanel.o ../obj/Edge.o ../obj/Graph.o ../obj/LargeGraph.o ../obj/MultiGraph.o ../obj/HMM.o ../obj/MultiHMM.o ../obj/AlphaHMM.o ../obj/AlphaHMMlegacy.o ../obj/Node.o ../obj/NextGen.o ../obj/HLAtypes.o ../obj/simulationSuite.o ../obj/readSimulator.o ../obj/Validation.o ../obj/LocusCodeAllocation.o ../obj/LargeLocusCodeAllocation.o ../obj/Utilities.o ../obj/DeBruijnGraph.o ../obj/DeBruijnElement.o ../obj/basic.o ../obj/binarykMer.o ../obj/Hsh.o ../obj/GraphAligner.o ../obj/GraphAlignernonAffine.o ../obj/GraphAlignerAffine.o ../obj/GraphAlignerendsFree.o ../obj/GraphAlignerUnique.o ../obj/coveredIntervals.o ../obj/GraphAndEdgeIndex.o ../obj/UniqueAlignerTests.o ../obj/readFilter.o ../obj/filterLongOverlappingReads.o ../obj/GraphAndIndex.o ../obj/AlignerTests.o ../obj/VirtualNW.o ../obj/VirtualNWUnique.o ../obj/MHC-PRG.o -o ../bin/MHC-PRG /${boostpath}/boost_1.52.0/lib/libboost_random.so /${boostpath}/boost_1.52.0/lib/libboost_filesystem.so /${boostpath}/boost_1.52.0/lib/libboost_system.so /${bamtoolspath}/bamtools/lib/libbamtools.so /{bamtoolspath}/bamtools/lib/libbamtools-utils.a /${ziplibpath}/zlib_1.2.8/lib/libz.a;

**With the following error:
**
../obj/readFilter.o: In function `getBAMregions(std::string)':
readFilter/readFilter.cpp:1265: undefined reference to `BamTools::BamReader::Open(std::string const&)'
../obj/readFilter.o: In function `filterBAM(int, std::string, std::string, std::string, std::function<bool (fastq_readPair const&, bool)>*, std::function<void (fastq_readPair const&)>*, bool) [clone ._omp_fn.0]':
/readFilter/readFilter.cpp:888: undefined reference to `BamTools::BamReader::GetReferenceID(std::string const&) const'
../obj/readFilter.o: In function `filterBAM(int, std::string, std::string, std::string, std::function<bool (fastq_readPair const&, bool)>*, std::function<void (fastq_readPair const&)>*, bool)':
readFilter/readFilter.cpp:806: undefined reference to `BamTools::BamReader::Open(std::string const&)'
readFilter/readFilter.cpp:829: undefined reference to `BamTools::BamReader::Open(std::string const&)'
collect2: error: ld returned 1 exit status

I'm not familiar with c libraries, any suggestion?

Many thanks!

**Comment by AlexanderDilthey** [comment]
Relative to our makefile, you've got libbamtools.so and libbamtools-utils.a the wrong way around - i.e. it should be libbamtools.a and libbamtools-utils.so. Can you try whether changing this helps?

**Comment by yluo86** [comment]
That seems to do the trick. Thanks!

I was able to run 
./nextGenInferenceVariGraph.pl --graph ../tmp2/GS_nextGen/varigraph3 --sample AA02O9Q_Z2 --kmer 31

successfully. However, another error occurred after following the installation steps with command (../bin/MHC-PRG domode nextGenInference ../tmp2/GS_nextGen/varigraph3/graph.txt.kmers_31 ../tmp2/GS_nextGen/varigraph3/graph.txt.kmers_31.kMersReferenceCorrected ../tmp/kMerCount__GS_nextGen_varigraph3_AA02O9Q_Z2_31_required.binaryCount --labelonly --genotypingMode 8
)

**../bin/MHC-PRG: error while loading shared libraries: libboost_random.so.1.52.0: cannot open shared object file: No such file or directory
**
Does it mean MHC-PRG was not build properly?
