### ISSUE TITLE
Compilation Error with g++-4.8 on Mac. OS

### ISSUE THREAD

**Issue by drmaly** [AlexanderDilthey/MHC-PRG#12]
While trying to compile, I got the following error. I appreciate any ideas on solving this 

humgen-no-iMac:MHC-PRG waleed$ make all
g++-4.8 -I/usr/local/Cellar/boost/1.60.0_1/ -IGraph -I/Users/waleed/Downloads/bamtools/include -I/Users/waleed/Downloads/bamtools/src  -ggdb -O2 -fopenmp -std=gnu++0x -fstack-protector-all Utilities.cpp -c -o ../obj/Utilities.o
Utilities.cpp: In static member function 'static std::mapstd::basic_string<char, std::basic_string<char> > Utilities::readFASTA(std::string, bool)':
Utilities.cpp:553:2: error: reference to 'ifstream' is ambiguous
  ifstream FASTAstream;
  ^
In file included from /usr/local/include/boost/filesystem/string_file.hpp:14:0,
                 from /usr/local/include/boost/filesystem.hpp:19,
                 from Utilities.cpp:22:
/usr/local/include/boost/filesystem/fstream.hpp:169:32: note: candidates are: typedef class boost::filesystem::basic_ifstream<char> boost::filesystem::ifstream
   typedef basic_ifstream<char> ifstream;
                                ^
In file included from /usr/local/Cellar/gcc/4.8.5/include/c++/4.8.5/bits/localefwd.h:41:0,
                 from /usr/local/Cellar/gcc/4.8.5/include/c++/4.8.5/string:43,
                 from Utilities.h:12,
                 from Utilities.cpp:8:
/usr/local/Cellar/gcc/4.8.5/include/c++/4.8.5/iosfwd:157:34: note:                 typedef class std::basic_ifstream<char> std::ifstream
   typedef basic_ifstream<char>   ifstream;
                                  ^
Utilities.cpp:553:11: error: expected ';' before 'FASTAstream'
  ifstream FASTAstream;
           ^
Utilities.cpp:555:2: error: 'FASTAstream' was not declared in this scope
  FASTAstream.open(file.c_str());
  ^
make: **\* [../obj/Utilities.o] Error 1

**Comment by AlexanderDilthey** [comment]
Interesting. Can you try replacin

553: ifstream FASTAstream;

with

std::ifstream FASTAstream;

?

**Comment by drmaly** [comment]
Thank you very much Alexander that seems to fix this issue, however another one emerged which I could not resolve yet. 
 Here is the message i got:

humgen-no-iMac:MHC-PRG waleed$ make all
g++-4.8 -I/usr/local/Cellar/boost/1.60.0_1/ -IGraph -I/Users/waleed/Downloads/bamtools/include -I/Users/waleed/Downloads/bamtools/src  -ggdb -O2 -fopenmp -std=gnu++0x -fstack-protector-all MHC-PRG.cpp -c -o ../obj/MHC-PRG.o;
g++-4.8 -I/usr/local/Cellar/boost/1.60.0_1/ -IGraph -I/Users/waleed/Downloads/bamtools/include -I/Users/waleed/Downloads/bamtools/src  -ggdb -O2 -fopenmp -std=gnu++0x -fstack-protector-all ../obj/GenotypePanel.o ../obj/HaplotypePanel.o ../obj/Edge.o ../obj/Graph.o ../obj/LargeGraph.o ../obj/MultiGraph.o ../obj/HMM.o ../obj/MultiHMM.o ../obj/AlphaHMM.o ../obj/AlphaHMMlegacy.o ../obj/Node.o ../obj/NextGen.o ../obj/HLAtypes.o ../obj/simulationSuite.o ../obj/readSimulator.o ../obj/Validation.o ../obj/LocusCodeAllocation.o ../obj/LargeLocusCodeAllocation.o ../obj/Utilities.o ../obj/DeBruijnGraph.o ../obj/DeBruijnElement.o ../obj/basic.o ../obj/binarykMer.o ../obj/Hsh.o ../obj/GraphAligner.o ../obj/GraphAlignernonAffine.o ../obj/GraphAlignerAffine.o ../obj/GraphAlignerendsFree.o ../obj/GraphAlignerUnique.o ../obj/coveredIntervals.o ../obj/GraphAndEdgeIndex.o ../obj/UniqueAlignerTests.o ../obj/readFilter.o ../obj/filterLongOverlappingReads.o ../obj/GraphAndIndex.o ../obj/AlignerTests.o ../obj/VirtualNW.o ../obj/VirtualNWUnique.o ../obj/MHC-PRG.o -o ../bin/MHC-PRG /usr/local/Cellar/boost/1.60.0_1/lib/libboost_random.so /usr/local/Cellar/boost/1.60.0_1/lib/libboost_filesystem.so /usr/local/Cellar/boost/1.60.0_1/lib/libboost_system.so  /Users/waleed/Downloads/bamtools/lib/libbamtools.a /Users/waleed/Downloads/bamtools/lib/libbamtools-utils.so  /usr/local/Cellar/lzlib/1.7/;
g++-4.8: error: /usr/local/Cellar/boost/1.60.0_1/lib/libboost_random.so: No such file or directory
g++-4.8: error: /usr/local/Cellar/boost/1.60.0_1/lib/libboost_filesystem.so: No such file or directory
g++-4.8: error: /usr/local/Cellar/boost/1.60.0_1/lib/libboost_system.so: No such file or directory
g++-4.8: error: /Users/waleed/Downloads/bamtools/lib/libbamtools-utils.so: No such file or directory
make: *** [MHC-PRG] Error 1

I thought it is related to compatibility  with boost and bamtools versions and I installed the versions you mentioned here (boost 1.52), but I could not find any of the these files either (libboost_random.so, libboost_filesystem.so or libboost_system.so). The same also with bamtools, no file called libamtools-utils.so.

**Comment by AlexanderDilthey** [comment]
Just to confirm, the files (e.g. /usr/local/Cellar/boost/1.60.0_1/lib/libboost_random.so) do not actually exist on your system?

Have you built boost? Are there any files in the /usr/local/Cellar/boost/1.60.0_1/lib/ directory?

**Comment by drmaly** [comment]
Hi,

First am really sorry for the late response.
Responding to your questions, yes I built boost and also installed bamtools. There are many files in /usr/local/Cellar/boost/1.60.0_1/lib/ directory none of them with *.so suffix. However there are files like this:
libboost_random.a
libboost_random.dylib
libboost_filesystem.a
libboost_filesystem.dylib
libboost_system.a
libboost_system.dylib

And for bamtools there are such these file:
libbamtools-utils.a
libbamtools.a
libbamtools.dylib

Honestly, I have no experience in these compilation thing but reading some posts online suggested that for Mac OS *.dylib files can replace these  *.so files but not sure how that will be applied here!

**Comment by AlexanderDilthey** [comment]
Could you try these two experiments?

a) Replace all .so files in the makefile with the corresponding .dylib files
b) Replace all .so files in the makefile with the corresponding .a files
