### ISSUE TITLE
HLA Typing: BAM's not indexed?

### ISSUE THREAD

**Issue by mtutert** [AlexanderDilthey/MHC-PRG#15]
Hi,

I am currently running the HLA typing software portion of the MHC-PRG package. I set up the commands as described in the github descriptions however when I ran the program, I received this error:

MHC-PRG/20160217/MHC-PRG/tmp/hla/SAMPLEID does not seem to be indexed - please specify indexed BAM!

My BAM's are currently located in the SAMPLEID directory and they are indexed (there is both a bam and bam.bai folder located within).

Do you know what is potentially going wrong?

Thanks,
Marcus

**Comment by AlexanderDilthey** [comment]
Hi Marcus,

Can you give your exact command line?

**Comment by mtutert** [comment]
Hi Alexander,

Here is my command line:

./HLAtypeinference.pl --actions pnai --sampleIDs SAMPLEID --BAMs /.mounts/labs/awadallalab/private/hgibling/SOFT/MHC-PRG/20160217/MHC-PRG/tmp/hla/SAMPLEID --/.mounts/labs/awadallalab/private/mtutert

(The last path leads me to the directory that contains the fasta reference file hs37d5.fa for the reference genome. Please let me know if you need any more info.

Thanks,
Marcus

**Comment by AlexanderDilthey** [comment]
Isn't there a .bam missing in the --BAMs parameter, like in

/.mounts/labs/awadallalab/private/hgibling/SOFT/MHC-PRG/20160217/MHC-PRG/tmp/hla/SAMPLEID.bam

?

**Comment by mtutert** [comment]
Hi Alexander, 
 
Even when I change my command line to that (and include the .bam for the BAM's parameter):

/HLAtypeinference.pl --actions pnai --sampleIDs SAMPLEID --BAMs /.mounts/labs/awadallalab/private/hgibling/SOFT/MHC-PRG/20160217/MHC-PRG/tmp/hla/SAMPLEID.bam --referenceGenome /.mounts/labs/awadallalab/private/mtutert 

It still throws up the error:
terminate called after throwing an instance of 'std::runtime_error'
  what():  File /.mounts/labs/awadallalab/private/hgibling/SOFT/MHC-PRG/20160217/MHC-PRG/tmp/hla/SAMPLEID.bam does not seem to be indexed - please specify indexed BAM!

Are there any other syntax errors I am missing? The BAM's path currently leads to a folder with the indexed bam file (including the bai file) that we are looking at.

Thanks,
Marcus

**Comment by mtutert** [comment]
Hi Alexander,

That was the problem, thanks for the clarification on the syntax. I the output files now (best guess and pairs for each of the HLA classes), but I am unsure how to interpret them.

Can you please give your programs definition of Q1,Q2, AverageCoverage CoverageFirstDecile     MinimumCoverage and what should be considered "good scores" for each of them if you can?

Thanks,
Marcus

**Comment by AlexanderDilthey** [comment]
For the allele with Chromosome = 1, Q1 is the marginal probability of the allele specified being present at least once.

For the allele with Chromosome = 2, Q1 is the joint probability of the allele specified + the allele specified for Chromosome = 1.

Q2 is currently meaningless.

The Coverage fields should be self-explanatory - average coverage across the typed exons, the first decile of individual-position coverages across the typed exons, minimum coverage at any position across the typed exons.

Regarding the interpretation of the values, we don't have a whole lot of experience yet. It seems that Q1 deviating from 1 (say, < 0.9) typically indicates that something weird is going on (potentially novel alleles, mis-calls or absence of alleles for DRB3/4/5). I have only superficially examined the coverage values and so far not found them very useful.

**Comment by mtutert** [comment]
Hi Alexander, thanks for the help-much appreciated. I am still a bit confused however, as to how you correlate the allele probability with what the "Best Guesses" txt document outputted provides you with. For instance, attached is an example output with one of my provided bam files. The alleles are all grouped together under there respective locuses, and I don't see where the actual marginal probability for each allele is? Even with the "Paired Guesses" document, all I see is "Cluster ID", "P", "LL", "Mismatches Avg" (which if you could also explain to me there formulations in your code would be helpful). Could you help me analyze this output further briefly if you don't mind?

[HLA Best Guesses.docx](https://github.com/AlexanderDilthey/MHC-PRG/files/292645/HLA.Best.Guesses.docx)

**Comment by mtutert** [comment]
Hi Alexander, any updates on your labs end on the interpretation of lab results?

**Comment by AlexanderDilthey** [comment]
Hey, sorry, I had missed your earlier message!

In your example, 0.0148029 is the quality value of the first HLA-A allele - which means that the call is no good!

What type of input data is this based on?

**Comment by mtutert** [comment]
Hi Alexander,

No worries at all. So does this mean there is likely some bug here since across the locuses from A-C there isn't a substantially high number for Q1? This is based on WGS (bams) from AML data in a fellows laboratory. I will try to run it on the rest of the samples tomorrow.

For locuses B and C though when it says " B*07:02:01;B*07:02:06;B*07:02:09;B*07:120;B*07:128;B*07:129;B*07:130;B*07:156;B*07:161N;B*07:169;B*07:44;B*07:49N;B*07:58;B*07:59;B*07:61 " and gives me the corresponding score, I am confused by how to interpret this? I thought you mentioned that this is the marginal/joint probability of a allele being present but since this is multiple alleles I am confused as to how to separate this and get the best results for one allele in locus B (chromosome 1 or 2)

**Comment by AlexanderDilthey** [comment]
Regarding the list of alleles: HLA*PRG emulates classical HLA typing at G group resolution (http://hla.alleles.org/alleles/g_groups.html) - whenever you see a list of alleles like this, they are in the same G group and they are treated as one allele (sometimes there are minor descrepancies between the G groups as defined by IMGT and the groups used by HLA*PRG - these are technical artefacts that come from the fact that HLA*PRG defines alleles relative to a PRG of the HLA). This is biologically reasonable because all G group alleles have the sequence at the peptide binding site, i.e. they are likely to exhibit very similar peptide binding affinities. If you update to the most recent version, HLA*PRG will also emit a file where these lists of alleles are replaced with G group alleles (i.e., they are easier to parse).

Now, regarding the output you got: the coverage columns also indicate *very* low coverage - you should see at (the very) least something like 20x. As we discuss in the preprint, HLA*PRG has been optimized for WGS data with >=30x coverage (and a PCR-free protocol).

Without seeing your BAMs, I can only speculate on what is going on here. Low coverage in general seems a possible explanation, or perhaps the BAM has been regionally filtered?

**Comment by mtutert** [comment]
Hi Alexander,

I did regionally filter the BAM (for chromosome 6 just due to time constraints for that day), which I realize now was not smart...I will try again with the full WGS sequencing and the fully indexed bam. The coverage of the bam is 30x so it should hopefully work out and I'll get the coverage like you say.

Thank you for the description of the G group resolution of the HLA-PRG allele list, I updated to the most recent version of the code and I'll try it again.

Thanks for all your help!
Marcus

**Comment by AlexanderDilthey** [comment]
Hi Marcus,

Regional filtering can be done, but
- make sure to include unmapped reads if you do and
- if your reference genome contains multiple MHC haplotypes, make sure to include all reads from them as well

... and in addition to these a filter like chr6:28000000-36000000 should do.

Let me know if you run into problems, happy to help tracking down issues should they arise!

Alex
