### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by MUppal** [AlexanderDilthey/MHC-PRG#18]
Hi Alex,

Thanks so much for being so responsive to users, and for answering my question on Twitter. I'm having trouble with compiling the program. I'm using gcc 5.1, boost 1.59, and the bamtools version recommended in the README. When I do 'make all' I receive the following error:

gcc -xc++ -lstdc++ -shared-libgcc -I/home/mdu2002/boost-1.59.0/ -IGraph -I/home/mdu2002/bamtools/include -I/home/mdu2002/bamtools/src  -ggdb -O2 -fopenmp -std=gnu++0x -fstack-protector-all NextGen/readSimulator.cpp -c -o ../obj/readSimulator.o
NextGen/readSimulator.cpp:22:42: fatal error: boost/random/random_device.hpp: No such file or directory
 #include <boost/random/random_device.hpp>
                                          ^
compilation terminated.
make: **\* [../obj/readSimulator.o] Error 1

I've checked my installation of boost, and the file random_device.hpp is exactly where it should be, so I'm not sure what the underlying issue is. Any insight would be greatly appreciated.

**Comment by AlexanderDilthey** [comment]
This is a problem that is related to the path of the Boost libraries.

Can you confirm that the following file exists on your machine:

/home/mdu2002/boost-1.59.0/boost/random/random_device.hpp

**Comment by MUppal** [comment]
Yes, the file is there, so I'm not sure what the underlying problem is. It exists in the following directory:
/home/mdu2002/boost-1.59.0/include/boost/random/

I've also discovered that building bamtools (both the the current version and the commit that you pointed to in the README) does not produce the file libbamtools-utils.so

I'm unsure how to proceed.

**Comment by AlexanderDilthey** [comment]
So this is exactly the point - the file exists, but not in the location I mentioned in my previous message.

You see the -I switch in the make command above? Specifially, the '-I/home/mdu2002/boost-1.59.0' part?

What happens is that the file boost/random/random_device.hpp is searched for *relative to this path* (and all other include paths).

You need to modify the makefile and specify '/home/mdu2002/boost-1.59.0/include/' instead of '/home/mdu2002/boost-1.59.0'

**Comment by MUppal** [comment]
Hi Alex,
That helped me move farther along with the build process (though it generated a bunch of warnings), but like in this issue (https://github.com/AlexanderDilthey/MHC-PRG/issues/12), I lack libbamtools-utils.so from my build of bamtools. I made sure to build the specific commit you outlined in the README, but it still builds without that particular .so file. Do you have any insight on the matter?

**Comment by AlexanderDilthey** [comment]
Hmmm... can you confirm that there is no libbamtools.a?

**Comment by MUppal** [comment]
The file libbamtools.a exists in the /bamtools/lib directory. The following are the contents of the directory:
libbamtools.a
libbamtools.so.2.3.0
libbamtools-utils.a
libjsoncpp.a

**Comment by AlexanderDilthey** [comment]
So try compiling with libbamtools.a and  libbamtools-utils.a

**Comment by MUppal** [comment]
Hi Alex,
Like I mentioned in my previous answer, I tried doing so, but I keep receiving a long, complex error message like the following:
../obj/GenotypePanel.o:7904:4: error: stray ‘\377’ in program
../obj/GenotypePanel.o:7904:4: error: stray ‘\1’ in program
../obj/GenotypePanel.o:7904:19: warning: null character(s) ignored
    A    Q      ,     
                   ^
That's just a snippet of the error message.

**Comment by AlexanderDilthey** [comment]
Just to make sure we're on the same page, you mentioned libbamtools.so.2.3.0 and libbamtools-utils.a in your message, but explicitly NOT libbamtools.a - I promise this is the last time I mention this ;-), but just in case we've had a misunderstanding here it would be good if you tried to compile using only the .a files.

In the following I assume that this is what you've been doing all along.

A bit of Googling around seems to indicate that this might be related to problems with the language dialect - e.g. that the compiler might assume that you are trying to compile Objective-C++. Or perhaps these weird characters (could be Unicode) are now really in the program file - they could have been introduced when opening and saving the source code files in an editor.

Do you observe these problems when compiling or when linking?
