### ISSUE TITLE
request on accommodating CRAM format

### ISSUE THREAD

**Issue by yluo86** [AlexanderDilthey/MHC-PRG#19]
Hi Alex,

I'm planning to apply HLA_PRG  on a set of WGS samples in CRAM format. Does the current version of HLA_PRG support CRAM files?

Many thanks,

Yang

**Comment by AlexanderDilthey** [comment]
Hi Yang,

We currently don't support CRAM. It is a good suggestion for HLA*PRG:02.

In the meantime, the easiest way to go about this is to extract all reads from chr6:28000000-34000000, all unmapped reads and reads from all MHC ALT contigs (and potentially HLA alleles depending on what reference genome you use) and re-map this set to obtain BAM format (this is fast, as you're only re-mapping a small number of reads).

Alex

**Comment by yluo86** [comment]
Hi Alex,

Thanks for the suggestion. A naive question: what do you use for merging these BAM files? I used **samtools merge**, but it seems to create duplicate read IDs when the unmapped reads also mapped to the extract MHC region, which then causes problems with HLA*PRG:

_There is a problem with the read IDs in this BAM.
Read ID: RG1 / RG1/2
whichMate: 2
thisPair.have1: 0 with ID 
thisPair.have2: 1 with ID RG1/2_

I've tried re-sorting the BAM by their RG name, removing duplicate reads, re-sorting the BAM by its coordinate position again. But it seems to be quite inefficient. Any better way to do this?

Many thanks,

Yang

**Comment by AlexanderDilthey** [comment]
Hi Yang,

At what point exactly does the BAM merging come in? Here is my understanding of what you do, please correct if I've got a step wrong:

1. Use samtools view to get reads from MHC + unmapped -> temporary BAM
2. Use (e.g.) Picard to extract FASTQ from temporary BAM
3. Re-map extracted FASTQ to obtain BAM

Does the mergin happen after a parallelization step for 3.?

Just thinking: could one also use Step 1 to output BAM directly from CRAM?

Alex

**Comment by yluo86** [comment]
Hi Alex,

I've split Step 1 into two BAMs (and yes, Step 1 can output BAM directly from CRAM):
 _samtools view MHC all.cram -> MHC.bam
 samtools view unmapped.cram -> unmapped.bam_

and the merging steps comes afterwards:
 _samtools merge output.bam MHC.bam unmapped.bam_

Do I need to do remapping myself before feeding it to HLA*PRG? i.e. Step 2 and 3.

Thanks,

Yang

**Comment by yluo86** [comment]
Hi Alex,

I did what you recommended, i.e. remap extracted FASTQ to obtain BAM, however, the HLA*PRG result looks rather strange:

######
# cat R1_bestguess.txt
Locus	Chromosome	Allele	Q1	Q2	AverageCoverage	CoverageFirstDecile	MinimumCoverage
A	1	A*01:01:01:01;A*01:01:01:02N;A*01:01:38L;A*01:01:51;A*01:04N;A*01:103;A*01:107;A*01:109;A*01:132;A*01:141;A*01:142;A*01:22N;A*01:32;A*01:37;A*01:45;A*01:56N;A*01:81;A*01:87N	0.000897263	-0	0	0	0
A	2	A*01:01:01:01;A*01:01:01:02N;A*01:01:38L;A*01:01:51;A*01:04N;A*01:103;A*01:107;A*01:109;A*01:132;A*01:141;A*01:142;A*01:22N;A*01:32;A*01:37;A*01:45;A*01:56N;A*01:81;A*01:87N	4.02721e-07	-0	0	0	0
B	1	B*07:02:01;B*07:02:06;B*07:02:09;B*07:120;B*07:128;B*07:129;B*07:130;B*07:156;B*07:161N;B*07:169;B*07:44;B*07:49N;B*07:58;B*07:59;B*07:61	0.000684932	-0	0	0	0
B	2	B*07:02:01;B*07:02:06;B*07:02:09;B*07:120;B*07:128;B*07:129;B*07:130;B*07:156;B*07:161N;B*07:169;B*07:44;B*07:49N;B*07:58;B*07:59;B*07:61	2.34646e-07	-0	0	0	0
C	1	C*01:02:01;C*01:02:02;C*01:02:11;C*01:02:12;C*01:02:14;C*01:02:15;C*01:02:23;C*01:25;C*01:44;C*01:82;C*01:83;C*01:84	0.0010582	-0	0	0	0
C	2	C*01:02:01;C*01:02:02;C*01:02:11;C*01:02:12;C*01:02:14;C*01:02:15;C*01:02:23;C*01:25;C*01:44;C*01:82;C*01:83;C*01:84	5.60191e-07	-0	0	0	0
DQA1	1	DQA1*01:01:01;DQA1*01:01:02;DQA1*01:04:01:01;DQA1*01:04:01:02;DQA1*01:04:02;DQA1*01:05;DQA1*01:12	0.111111	-0	0	0	0
DQA1	2	DQA1*01:01:01;DQA1*01:01:02;DQA1*01:04:01:01;DQA1*01:04:01:02;DQA1*01:04:02;DQA1*01:05;DQA1*01:12	0.00653595	-0	0	0	0
DQB1	1	DQB1*02:01:01;DQB1*02:01:08;DQB1*02:02:01;DQB1*02:02:02;DQB1*02:04;DQB1*02:06;DQB1*02:09;DQB1*02:10	0.0056338	-0	0	0	0
DQB1	2	DQB1*02:01:01;DQB1*02:01:08;DQB1*02:02:01;DQB1*02:02:02;DQB1*02:04;DQB1*02:06;DQB1*02:09;DQB1*02:10	1.59147e-05	-0	0	0	0
DRB1	1	DRB1*01:01:01;DRB1*01:50	0.0014782	-0	0	0	0
DRB1	2	DRB1*01:01:01;DRB1*01:50	1.09334e-06	-0	0	0	0
##########

Coverage are all 0s, any idea how to solve this?

Thanks,

Yang

**Comment by AlexanderDilthey** [comment]
Hi Yang,

Sorry, this was a misunderstanding - instead of 'MHC', you need to use the names and coordinates of the MHC-relevant contigs in the reference genome used for producing the CRAM files. To get the unmapped read, I think you need to filter by BAM flags.

Alex

**Comment by yluo86** [comment]
Thanks Alex, it's working now. Just some silly bugs when merging two BAM files.

Yang
