### ISSUE TITLE
output MHC-PRG

### ISSUE THREAD

**Issue by fabiennejh** [AlexanderDilthey/MHC-PRG#26]
Hello,

I'm trying to use MHC-PRG and I have a warning in the end of the process that I don't understand. I have also a second output file called R1_bestguess_G.txt. Could you please help me to understand the error mesage (and to fix it), and to explain me what's this second bestguess file ?

Thank you
Fabienne

## Message d'erreur

Warning: Can't G-translate: A*01:52N; have only things like A*01:01:01:01Warning: Can't G-translate: A*01:67; have only things like A*01:01:01:01Warning: Can't G-translate: A*02:02; have only things like A*01:01:01:01Warning: Can't G-translate: A*02:06:01; have only things like A*01:01:01:01Warning: Can't G-translate: A*02:113N; have only things like A*01:01:01:01Warning: Can't G-translate: A*02:153; have only things like A*01:01:01:01Warning: Can't G-translate: A*02:157; have only things like A*01:01:01:01Warning: Can't G-translate: A*02:289; have only things like A*01:01:01:01Warning: Can't G-translate: A*02:64; have only things like A*01:01:01:01Warning: Can't G-translate: A*03:154; have only things like A*01:01:01:01Warning: Can't G-translate: A*03:157; have only things like A*01:01:01:01Warning: Can't G-translate: A*03:44; have only things like A*01:01:01:01Warning: Can't G-translate: A*

**Comment by AlexanderDilthey** [comment]
Hi Fabienne,


But the file R1_bestguess_G.txt gets populated with sensible calls?


Generally speaking R1_bestguess_G.txt and R1_bestguess.txt represent identical call sets. The difference between the two files is that we try to translate the allele group calls from R1_bestguess.txt into the IMGT-defined G groups for R1_bestguess_G.txt. You can read up on G groups at http://hla.alleles.org/alleles/g_groups.html. This translation process doesn't always work perfectly, which is what these warnings refer to. The column "perfectG" in R1_bestguess_G.txt will tell you (for each locus) whether the calls from R1_bestguess.txt could be translated perfectly into G group resolution.


Therefore, as long as R1_bestguess_G.txt  looks sensible, you can ignore the warnings.


Best,

Alex

________________________________
Von: fabiennejh <notifications@github.com>
Gesendet: Freitag, 31. März 2017 11:28
An: AlexanderDilthey/MHC-PRG
Cc: Subscribed
Betreff: [AlexanderDilthey/MHC-PRG] output MHC-PRG (#26)


Hello,

I'm trying to use MHC-PRG and I have a warning in the end of the process that I don't understand. I have also a second output file called R1_bestguess_G.txt. Could you please help me to understand the error mesage (and to fix it), and to explain me what's this second bestguess file ?

Thank you
Fabienne

Message d'erreur

Warning: Can't G-translate: A01:52N; have only things like A01:01:01:01Warning: Can't G-translate: A01:67; have only things like A01:01:01:01Warning: Can't G-translate: A02:02; have only things like A01:01:01:01Warning: Can't G-translate: A02:06:01; have only things like A01:01:01:01Warning: Can't G-translate: A02:113N; have only things like A01:01:01:01Warning: Can't G-translate: A02:153; have only things like A01:01:01:01Warning: Can't G-translate: A02:157; have only things like A01:01:01:01Warning: Can't G-translate: A02:289; have only things like A01:01:01:01Warning: Can't G-translate: A02:64; have only things like A01:01:01:01Warning: Can't G-translate: A03:154; have only things like A01:01:01:01Warning: Can't G-translate: A03:157; have only things like A01:01:01:01Warning: Can't G-translate: A03:44; have only things like A01:01:01:01Warning: Can't G-translate: A*

**Comment by fabiennejh** [comment]
Thank you for your answer. 
I've looked carefully into the files, and what is surprising to me is that the calls in the bestguess_G file don't correspond to the calls of the R1_bestguess IMGT-defined G groups. In this case, which of the two should I consider as the most reliable ?

For example 
in R1_bestguess : 
DRB1	1	DRB1*03:01:01:01;DRB1*03:01:01:02;DRB1*03:01:08	1	-37	108.102	88	71	1	0.000776502	0
DRB1	2	DRB1*04:03:01	1	-37	108.102	88	71	1	0.000776502	0

in R1_bestguess_G : 
DRB1	1	DRB1*07:01:01G	1	-891	138.599	87	76	1	0.0147198	10	1
DRB1	2	DRB1*15:02:01	1	-891	138.599	87	76	1	0.0147198	10	0

Thank you 
Fabienne

**Comment by AlexanderDilthey** [comment]
Hi Fabienne,

This looks weird indeed. Are you sure that these two examples are from the same sample? The two example calls you provided have different values for the AverageCoverage column, which should, generally speaking, not be the case. If they are from the same sample, could you send me the complete R1_bestguess / R1_bestguess_G files, so I can check in detail what has happened?

**Comment by fabiennejh** [comment]
Hi Alexander,

You're right, I've tested several examples and there was a confusion into the output files, I'm sorry.

Thank you for your concern.
Fabienne
