### ISSUE TITLE
Error during make all for Graph/Graph.cpp 

### ISSUE THREAD

**Issue by robrollback** [AlexanderDilthey/MHC-PRG#7]
I changed paths to my local boost and bamtools. Compiling of GenotypePanel.cpp, HalplotypePanel.cpp, and Edge.cpp completed successfully. Graph.cpp did not.

g++ -I/lb/project/mugqic/analyste_dev/software/boost/1.52 -IGraph -I/lb/project/mugqic/analyste_dev/software/bamtools/2.3.0/include -I/lb/project/mugqic/analyste_dev/software/bamtools/2.3.0/src  -ggdb -O2 -fopenmp -std=gnu++0x -fstack-protector-all Data/GenotypePanel.cpp -c -o obj/GenotypePanel.o
g++ -I/lb/project/mugqic/analyste_dev/software/boost/1.52 -IGraph -I/lb/project/mugqic/analyste_dev/software/bamtools/2.3.0/include -I/lb/project/mugqic/analyste_dev/software/bamtools/2.3.0/src  -ggdb -O2 -fopenmp -std=gnu++0x -fstack-protector-all Data/HaplotypePanel.cpp -c -o obj/HaplotypePanel.o
g++ -I/lb/project/mugqic/analyste_dev/software/boost/1.52 -IGraph -I/lb/project/mugqic/analyste_dev/software/bamtools/2.3.0/include -I/lb/project/mugqic/analyste_dev/software/bamtools/2.3.0/src  -ggdb -O2 -fopenmp -std=gnu++0x -fstack-protector-all Graph/Edge.cpp -c -o obj/Edge.o
g++ -I/lb/project/mugqic/analyste_dev/software/boost/1.52 -IGraph -I/lb/project/mugqic/analyste_dev/software/bamtools/2.3.0/include -I/lb/project/mugqic/analyste_dev/software/bamtools/2.3.0/src  -ggdb -O2 -fopenmp -std=gnu++0x -fstack-protector-all Graph/Graph.cpp -c -o obj/Graph.o
Graph/Graph.cpp: In member function ‘void Graph::graphViz(int, int, std::string)’:
Graph/Graph.cpp:57: error: expected primary-expression before ‘[’ token
Graph/Graph.cpp:57: error: expected primary-expression before ‘]’ token
Graph/Graph.cpp:57: error: expected primary-expression before ‘int’
Graph/Graph.cpp:57: error: expected primary-expression before ‘*’ token
Graph/Graph.cpp:57: error: ‘n’ was not declared in this scope
Graph/Graph.cpp:57: error: unable to deduce ‘auto’ from ‘<expression error>’
Graph/Graph.cpp:57: error: expected ‘,’ or ‘;’ before ‘{’ token
Graph/Graph.cpp:1355: error: expected ‘}’ at end of input
make: *** [obj/Graph.o] Error 1

**Comment by AlexanderDilthey** [comment]
Can you try pulling the most recent version? (Pushed an update yesterday)

If this doesn't help: which version of g++ are you using?

**Comment by robrollback** [comment]
Thanks for that. I've pulled Graph.cpp and recompiled. Still the same issue. So it could be the g++ version.

g++ -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)

**Comment by robrollback** [comment]
Compiled successfully with 4.7.2. Thanks for your help.
