### ISSUE TITLE
MHC-PRG for GRCh38

### ISSUE THREAD

**Issue by wangyugui** [AlexanderDilthey/MHC-PRG#8]
Is it OK to run MHC-PRG with GRCh38 such as Ensembl GRCh38.81?

Can we use the data package of GRCh37 , or should we create the data package for GRCh38?
1)mhc_ref_8_haplotypes/pgf_ref.fasta
   extract from chr6?

2)mhc_ref_8_haplotypes/alignment/all_aligned.fasta
  extract from GRCh38 ALT contigs?
   CHR_HSCHR6_MHC_APD_CTG1
   CHR_HSCHR6_MHC_COX_CTG1
   CHR_HSCHR6_MHC_DBB_CTG1
   CHR_HSCHR6_MHC_MANN_CTG1
   CHR_HSCHR6_MHC_MCF_CTG1
   CHR_HSCHR6_MHC_QBL_CTG1
  CHR_HSCHR6_MHC_SSTO_CTG1

3)segments.txt/positions.txt
  how to build them?
  from ftp://ftp.ebi.ac.uk/pub/databases/ipd/imgt/hla/alignments/?

**Comment by AlexanderDilthey** [comment]
Unfortunately we don't support GRCh38 yet, and re-building the underlying alignments is a lot of work. We might release an updated PRG for GRCh38 towards the end of the year.

That being said, I would imagine that this shouldn't be too much of an issue in most practical scenarios. If you want to interrogate the large structural features of the MHC, the VCFs produced by MHC-PRG will need custom post-processing in any case, and I would imagine that one could integrate a translate-2-GRCh38 step if desired.

**Comment by wangyugui** [comment]
Can you share more document for data building?
Even if GRCh38 data set is released,  there is yet needs  for build data set with newest HLA database?

**Comment by AlexanderDilthey** [comment]
Solution: use HLA*PRG:LA

https://github.com/AlexanderDilthey/HLA-PRG-LA/blob/master/README.md
