### ISSUE TITLE
PRG-HLA report reference allele sequence and variants

### ISSUE THREAD

**Issue by novutao** [AlexanderDilthey/MHC-PRG#9]
Hi Alex, how can I generate pseduo allele sequence from the reference graph and call variants based on the aligned reads?
I don't know how to interpret the allele clusters reported in R1_bestguess.txt. Does it mean each allele is equally likely or does it mean the most likely allele contains all the variants in the allele cluster?
Also could you please provide some notes on the content/structure of R1_pileup_$LOCUS.txt and reads.p.n.aligned
Thanks a lot!

**Comment by AlexanderDilthey** [comment]
Hi Tao,

Sorry for the delay in responding - I had been away for some time.

I assume we're talking about HLA*PRG here and not about MHC*PRG?

There are two separate features:

First, HLA typing (which just covers exons 2/3 for HLA class I and exon 2 for HLA class II). HLA typing estimates the best diploid HLA allele call and is limited to the (thousands of) alleles currently catalogued in IMGT/HLA. You will find the results from HLA typing in R1_bestguess.txt. As HLA typing only covers the exons encoding the peptide binding site (PBS), we can't distinguish between alleles that have the same PBS sequence - hence the "clustering". This sounds like a limitation, but note that gold-standard HLA typing (SBT) does exactly the same thing, and that most phenotypic variation correlating with HLA types is assumed to come from genetic variation at the PBS.

Second, HLA gene sequence estimation: an algorithm that attempts to estimate the sequence of the complete HLA gene, i.e. including all exons and introns. This feature is currently not activated - with short reads, we can't really validate the output. If active, it will produce R2_* files, and also variant call files. If you are specifically interested in this feature, we could think about ways to activate and validate it.

Regarding the two files: R1_pileup_$LOCUS.txt is just a per-position pileup file of aligned reads, and reads.p.n.aligned is a non-binary representation of the read alignments. If you are interested in further particulars, I could probably produce some documentation on the file formats.
